### ISSUE TITLE
Looking up precedence by case number

### ISSUE THREAD

**Issue by corywalker** [cznic/wl#11]
Is it possible to look up precedence values or orders by using the case number? My ultimate goal is to check for things like, "Is multiplication higher precedence than addition?"

In Expreduce's interface to this library, it already has a mapping from Heads to case numbers for the parser:

https://github.com/corywalker/expreduce/blob/e867a0330acff2319023f17864f4c801b2daa309/expreduce/interp.go#L178

**Comment by cznic** [comment]
@corywalker
Not at the moment, but it can be added as some table to the generated parser. Will try to come with some implementation and let's see if it's what you're after.

**Comment by cznic** [comment]
@corywalker Gentle ping.
