### ISSUE TITLE
Something odd with implicit multiplication

### ISSUE THREAD

**Issue by corywalker** [cznic/wl#4]
The first example is correct, the second is not. Looking into this...

In[7]:= 4*a^2

Out[7]= (4 * a^2)

In[8]:= 4a^2

Out[8]= (16 * a^2)

**Comment by corywalker** [comment]
Seems to be a special case of "Term '^' Term". Anything of that form seems to be reduced before when Expression ^ Expression would normally reduce.

**Comment by cznic** [comment]
Yeah, it's definitely a bug. From the docs:

> x^2y, like x^2 y, means (x^2) y

but

```
In[1]:= x^2y
&wl.Expression{
· Case: 48,
· Expression: &wl.Expression{
· · Case: 55,
· · Factor: &wl.Factor{
· · · Term: &wl.Term{
· · · · Case: 5,
· · · · Token: IDENT, "x",
· · · },
· · },
· },
· Expression2: &wl.Expression{
· · Case: 55,
· · Factor: &wl.Factor{
· · · Case: 1,
· · · Factor: &wl.Factor{
· · · · Term: &wl.Term{
· · · · · Case: 5,
· · · · · Token: IDENT, "y",
· · · · },
· · · },
· · · Term: &wl.Term{
· · · · Case: 8,
· · · · Token: INT, "2",
· · · },
· · },
· },
· Token: '^',
}
```

and

> x/2y, like x/2 y, means (x/2) y

but

```
In[2]:= x/2y
&wl.Expression{
· Case: 39,
· Expression: &wl.Expression{
· · Case: 55,
· · Factor: &wl.Factor{
· · · Term: &wl.Term{
· · · · Case: 5,
· · · · Token: IDENT, "x",
· · · },
· · },
· },
· Expression2: &wl.Expression{
· · Case: 55,
· · Factor: &wl.Factor{
· · · Case: 1,
· · · Factor: &wl.Factor{
· · · · Term: &wl.Term{
· · · · · Case: 5,
· · · · · Token: IDENT, "y",
· · · · },
· · · },
· · · Term: &wl.Term{
· · · · Case: 8,
· · · · Token: INT, "2",
· · · },
· · },
· },
· Token: '/',
}
```

**Comment by cznic** [comment]
I think the above commit is a first step in fixing this issue.

I'm afraid the other required changes to the grammar will mutate its structure considerably. Brace for Case fields numbering instability.

**Comment by cznic** [comment]
> Seems to be a special case of "Term '^' Term". Anything of that form seems to be reduced before when Expression ^ Expression would normally reduce.

My experiments seem to indicate that the solution is probably to partially rewrite the AST after reducing the `Expression '^' Expression` rule. That's feasible. All other approaches failed so far. WDYT?

PS: The same problem is in 'x/2y', it should equal `(x/2) y`. There are possibly more problems like this :-(

**Comment by corywalker** [comment]
I don't see an issue with rewriting the AST. I have not seen an attempt at parsing WL that does not have some form of rewrite after a parse step.

Case number changes are expected. They're not hard to update.

**Comment by cznic** [comment]
I'm in the middle of reinstalling my machine from scratch. It gave me an opportunity to think about this a bit more. After I finish preparing the box, I'll try an experiment such that

- If the just scanned token is not in the follow set for a given state but `'*'` is, unget the token and inject `'*'`.

It's similar to what we already do with newlines. If it's gonna work, it would make the AST even a bit more regular as the implicit multiplication AST will be the same as the explicit one.
